@startuml
title warmhouse container diagramm

top to bottom direction

!include ../C4/C4_Container.puml

'users
Person(User, "Registered User", "Standard registered user")

'system external
System(externalelements,"warmhouse end elements","Sensors hotpot, video, switch and etc.")
System_Ext(vendors,"vendor end elements","Sacribe vendor sensor, hopot, video, switch and etc.")
System_Ext(bank, "Bank System", "External bank for processing payments")
System_Ext(infosystem, "Info system smtp/telegram and etc.", "External system for userinfo")

' System
System(warmhouse, "warmhouse system", "System managing memberships, end element, database and payments")

' containers
System_Boundary(warmhouse, "warmhouse system") {
'UI
    Container(userwebApp, "UserWeb", "Code?", "Web for end user")
    Container(mobileApp, "Mobile App", "Code?", "Mobile end user interface")
    Container(techuserwebApp,"TechWeb","Code?","Web for admin and support user")

'API
    Container(upextdescription,"Ged data from vendor API", "Code?","Service for upload vendor element description")
    Container(adminendelement,"End User API", "Code?","Service for add, administration and trigger end element for end user")
    Container(streaming,"Sreaming API","Code?", "Streaming from house to end user")

'PaymentService
    Container(paymentservice, "PaymentService", "Code?", "Payment service")

'Auth
    Container(securitylist, "Security list and roles","Kerberos","Database for users and roles")
    Container(authService,  "Security Service","OAuth2", "Security Service")

'Data
    Container(endelementdatabase,"End DB","PostsreSQL","DB for vendor end element")
    Container(userdescriptiondatabase,"User DB","PostgreSQL","DB for user elements list and triggering")
    Container(userpaymentdata,  "PaymentData","PostgreSQL","Data about user payment")

' connect internal
' user
Rel(user, userwebApp, "Control and amninistrate end element")
Rel(user, mobileApp, "Control and amninistrate end element")
Rel(admin, techuserwebApp, "Administrate system, connect to vendor, payment control")
Rel(support, techuserwebApp, "Support end user")

'system from UI
Rel(userwebApp, adminendelement, "Contrao end element and rules")
Rel(userwebApp, streaming,"Streaming from video end element")
Rel(mobileApp, streaming,"Streaming from video end element")
Rel(mobileApp, adminendelement,"Streaming from video end element")

'System from system
Rel(techuserwebApp,upextdescription,"Upload description for end element")
Rel(upextdescription,endelementdatabase,"Upload vendor end element")

'Database
Rel(paymentservice,userpaymentdata,"History data about payment")
Rel(adminendelement,userdescriptiondatabase,"Control and create data from end element")
Rel(adminendelement,endelementdatabase,"Get info about end element")

'Auth
Rel(userwebApp,authService,"Security control and create jwt")
Rel(mobileApp,authService,"Security control and create jwt")
Rel(techuserwebApp,authService,"Security control and create jwt")
Rel(techuserwebApp,securitylist,"Administration and control security")
Rel(authService,securitylist,"Check roles")

'Payment
Rel(userwebApp,paymentservice,"Payment and conrole")
Rel(mobileApp,paymentservice,"Payment and conrole")
Rel(techuserwebApp,paymentservice, "control Payment")
}

'connect external
'system from UI
Rel(streaming,externalelements,"Get videosreaming")

'System from system
Rel(adminendelement,externalelements,"Control end element")
Rel(upextdescription,vendors,"Upload vendor end element")

'Payment
Rel(paymentservice,bank,"Payment control")

'info
Rel(paymentservice,infosystem,"Send user payment info")
Rel(authService,infosystem,"Send security info")
Rel(adminendelement,infosystem,"Send house info")

@enduml