@startuml
title Standard bank container diagramm

top to bottom direction

!include ../C4/C4_Container.puml

'users
Person(User, "Registered User", "Standard registered user")
Person(DepositManager,"Deposit manager", "Manager from Deposit department")

'system external
System_Ext(CB,"Central Bank","Send daily rate")
System_Ext(Telecom, "Telecom provider", "Telecom provider for send SMS")

' System
System(SMSGateway, "SMS Gateway", "SMS Gateway for generated and send sms code")
System(E_mailGateway, "e_mail system","e_mail system for get CB rate and notification system")
System(ABS,"ABS Standard Bank","Monolith ABS")

System(Security,"Security sytem for Standard Bank")

ContainerDb(PostgreSQL,"PostgreSQL Database", "New PostreSQL DB for deposite microservice")
ContainerDb(Oracle,"Database for old ABS")
System(Kafka,"Kafka brocker","New Kafka broker")
System(WebApp,"Web app for site","web App for Site")
System(InternetBank,"Standard internet bank", "Internal Standard internet bank")
System(SQLAdapter,"SQL Adatper to DataBase", "SQL Adapter for PostgreSQL")


System_Boundary(WebApp, "Web App") {
'UI
    Container(UserWebApp, "UserWeb", "React.js", "Web for end user")
'API
    Container(ServerSide,"Server side","SpringBoot","Web for admin and support user")
'connect internal
    Rel(UserWebApp, ServerSide, "Get static data and request for deposit")
'connect external

}

System_Boundary(InternetBank, "Web App") {
    'Container(Deposit,"Deposit microservice","New deposit microservice")
    Container(NewInternetBank,"New Internet bank","Django","New code for internet bank for deposit")
    Container(WebForInternetBank,"InternetBank web client","Node.js","Client for internet bank")
    Container(OldInternetBank,"Old internet bank","Old code for deposit")
    Container(InternetBankGateway,"Gateway for InternetBank","Gateway")

    Rel(NewInternetBank,SQLAdapter, "Data request", "SQL")
    Rel(InternetBankGateway,NewInternetBank,"request for deposit")
    Rel(InternetBankGateway,OldInternetBank,"Old Request")
    Rel(WebForInternetBank,InternetBankGateway,"Old Request")
}

'UI
Rel(User, UserWebApp,"Use Standard Bakn internet-bank", TLS)


 'Rel(ABS,E_mailGateway,"Get daily rate",pop3)
Rel(CB,E_mailGateway,"Send daily rate", "smtp")

Rel(User,WebForInternetBank,"Data for authenticated user")

Rel(NewInternetBank, SMSGateway,"Send request for SMS")

Rel(SMSGateway,Telecom,"Send SMS code and phone number")

Rel_U(Telecom,User,"Send SMS code")

Rel(NewInternetBank,E_mailGateway,"get daily rate","pop3")

Rel(SMSGateway, InternetBankGateway, "Return SMS code")

Rel(OldInternetBank, ABS,"Old request any format")
Rel(SQLAdapter, PostgreSQL,"Data request", "SQL")


Rel(SQLAdapter,ABS,"old format request","SQL")

Rel(ABS,Oracle,"Data from old ABS")

Rel(ServerSide,ABS,"Get static data by crone")

Rel(NewInternetBank,DepositManager,"Request to confirm rate")

Rel(ABS,Kafka,"Send data about client accounts")
Rel(NewInternetBank,Kafka,"subscribe to current acccouts")

'Rel_R(ServerSide,Security,"Authrntication user and get roles")
Rel(WebForInternetBank,Security,"Authrntication user and get roles")

@enduml